### ISSUE TITLE
Misleading readme

### ISSUE THREAD

**Issue by Faltenreich** [NinevaStudios/unity-google-maps-docs#9]
The [wiki](https://github.com/NinevaStudios/unity-google-maps-docs/wiki/Place-Picker-&-Place-Autocomplete) of the "Place Picker & Place Autocomplete" part of this wonderful library states that the "Places API" has been deprecated ("Since Google has deprecated its Places API and this functionality will be removed from the plugin very soon unfortunately.") but as far as I interpret the official documentation, only a fraction of Google Places will be deprecated: the Places Picker widget ("The Place Picker (Android, iOS) is deprecated as of January 29, 2019.").

Therefor the wiki should be updated to highlight that only the Place Picker is affected. Replacing the Places Autocomplete widget or network endpoints targeting the Places API is therefor currently not required. Please correct me if I am wrong.

Source:
- Places SDK for Android: Place Picker ([Android](https://developers.google.com/places/android-sdk/placepicker), [iOS](https://developers.google.com/places/ios-sdk/placepicker))

**Comment by TarasOsiris** [comment]
Hello @Faltenreich, you are partially right, there are two things happening: 1) Place picker is deprecated completely and 2) Places API will no longer be a part of Google Play Services but a separate library

![image](https://user-images.githubusercontent.com/3141378/55152740-ac875400-5159-11e9-8372-c50f53941007.png)

I have been investigating it and the new SDK has really a lot of dependencies that go along with it that's why I have made a decision to soon remove the Places API functionality from the current plugin. The place autocomplete in the deprecated version should still work.

![image](https://user-images.githubusercontent.com/3141378/55153241-a34ab700-515a-11e9-8afc-6eb28d460a6c.png)

**Comment by Faltenreich** [comment]
Sounds great! Thank you for the quick response and your awesome work!
